server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ropadb.czs4cgamg48z.ap-northeast-2.rds.amazonaws.com:3306/ropadb
    username: ropa
    password: ropa1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: DEBUG
    com.example.finalproject: DEBUG

